name: Run Python Release Action

on:
    workflow_dispatch:

jobs:
    run-python-release-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6
            - name: Run action
              uses: ./
              with:
                  command: release
                  changelog-args: '--commit-format "- {message} ([{abbr_hash}]({remote_url}/{abbr_hash}))" --output CHANGELOG.md'
                  bump-args: "minor"
                  tag-args: '--message-format "Release version {version}"'
                  github-token: ${{ secrets.GITHUB_TOKEN }}
